services:
    Linkin\Bundle\SwaggerResolverBundle\Builder\SwaggerResolverBuilder:
        arguments:
            - [] # validators
            - [] # normalizers
            - '%linkin_swagger_resolver.enable_normalization%'

    Linkin\Bundle\SwaggerResolverBundle\CacheWarmer\SwaggerConfigurationCacheWarmer:
        arguments:
            - '@Linkin\Bundle\SwaggerResolverBundle\Configuration\SwaggerConfigurationInterface'
        tags:
            - { name: kernel.cache_warmer }

    Linkin\Bundle\SwaggerResolverBundle\Configuration\SwaggerConfigurationInterface:
        alias: Linkin\Bundle\SwaggerResolverBundle\Configuration\SwaggerCachedConfiguration
    Linkin\Bundle\SwaggerResolverBundle\Configuration\SwaggerConfiguration:
        arguments:
            - '@Linkin\Bundle\SwaggerResolverBundle\Loader\SwaggerConfigurationLoaderInterface'
    Linkin\Bundle\SwaggerResolverBundle\Configuration\SwaggerCachedConfiguration:
        arguments:
            - '@Linkin\Bundle\SwaggerResolverBundle\Loader\SwaggerConfigurationLoaderInterface'
            - '%kernel.cache_dir%'
            - '%kernel.debug%'

    Linkin\Bundle\SwaggerResolverBundle\Factory\SwaggerResolverFactory:
        public: true
        arguments:
            - '@Linkin\Bundle\SwaggerResolverBundle\Builder\SwaggerResolverBuilder'
            - '@Linkin\Bundle\SwaggerResolverBundle\Configuration\SwaggerConfigurationInterface'
            - '@Symfony\Component\Routing\RouterInterface'
    linkin_swagger_resolver.factory:
        alias: Linkin\Bundle\SwaggerResolverBundle\Factory\SwaggerResolverFactory

    Linkin\Bundle\SwaggerResolverBundle\Merger\OperationParameterMerger:
        arguments:
            - '@Linkin\Bundle\SwaggerResolverBundle\Merger\MergeStrategyInterface'

    Linkin\Bundle\SwaggerResolverBundle\Merger\MergeStrategyInterface:
        alias: '@Linkin\Bundle\SwaggerResolverBundle\Merger\Strategy\StrictMergeStrategy'

    Linkin\Bundle\SwaggerResolverBundle\Merger\Strategy\CombineNameMergeStrategy: ~
    Linkin\Bundle\SwaggerResolverBundle\Merger\Strategy\ReplaceFirstWinMergeStrategy: ~
    Linkin\Bundle\SwaggerResolverBundle\Merger\Strategy\ReplaceLastWinMergeStrategy: ~
    Linkin\Bundle\SwaggerResolverBundle\Merger\Strategy\StrictMergeStrategy: ~

    Linkin\Bundle\SwaggerResolverBundle\Normalizer\BooleanNormalizer:
        tags:
            - { name: linkin_swagger_resolver.normalizer }
    Linkin\Bundle\SwaggerResolverBundle\Normalizer\IntegerNormalizer:
        tags:
            - { name: linkin_swagger_resolver.normalizer }
    Linkin\Bundle\SwaggerResolverBundle\Normalizer\NumberNormalizer:
        tags:
            - { name: linkin_swagger_resolver.normalizer }

    Linkin\Bundle\SwaggerResolverBundle\Validator\ArrayMaxItemsValidator:
        tags:
            - { name: linkin_swagger_resolver.validator }
    Linkin\Bundle\SwaggerResolverBundle\Validator\ArrayMinItemsValidator:
        tags:
            - { name: linkin_swagger_resolver.validator }
    Linkin\Bundle\SwaggerResolverBundle\Validator\ArrayUniqueItemsValidator:
        tags:
            - { name: linkin_swagger_resolver.validator }
    Linkin\Bundle\SwaggerResolverBundle\Validator\FormatDateValidator:
        tags:
            - { name: linkin_swagger_resolver.validator }
    Linkin\Bundle\SwaggerResolverBundle\Validator\FormatDateTimeValidator:
        tags:
            - { name: linkin_swagger_resolver.validator }
    Linkin\Bundle\SwaggerResolverBundle\Validator\FormatTimestampValidator:
        tags:
            - { name: linkin_swagger_resolver.validator }
    Linkin\Bundle\SwaggerResolverBundle\Validator\FormatTimeValidator:
        tags:
            - { name: linkin_swagger_resolver.validator }
    Linkin\Bundle\SwaggerResolverBundle\Validator\NumberMaximumValidator:
        tags:
            - { name: linkin_swagger_resolver.validator }
    Linkin\Bundle\SwaggerResolverBundle\Validator\NumberMinimumValidator:
        tags:
            - { name: linkin_swagger_resolver.validator }
    Linkin\Bundle\SwaggerResolverBundle\Validator\NumberMultipleOfValidator:
        tags:
            - { name: linkin_swagger_resolver.validator }
    Linkin\Bundle\SwaggerResolverBundle\Validator\StringMaxLengthValidator:
        tags:
            - { name: linkin_swagger_resolver.validator }
    Linkin\Bundle\SwaggerResolverBundle\Validator\StringMinLengthValidator:
        tags:
            - { name: linkin_swagger_resolver.validator }
    Linkin\Bundle\SwaggerResolverBundle\Validator\StringPatternValidator:
        tags:
            - { name: linkin_swagger_resolver.validator }

    Linkin\Bundle\SwaggerResolverBundle\ModelDescriber\ObjectModelDescriber:
       arguments:
           - '@property_info'
           - '@annotation_reader'
           - !tagged { tag: nelmio_api_doc.object_model.property_describer }
       tags:
           - { name: nelmio_api_doc.model_describer, priority: 250 }
