imports:
    - { resource: ./validators.yaml }
    - { resource: ./normalizers.yaml }
    - { resource: ./merge_strategies.yaml }

services:
    linkin_swagger_resolver.openapi_resolver_factory:
        class: Linkin\Bundle\SwaggerResolverBundle\Factory\OpenApiResolverFactory
        public: true
        arguments:
            - '@linkin_swagger_resolver.openapi_resolver_builder'
            - '@linkin_swagger_resolver.openapi_configuration'
            - '@router'

    linkin_swagger_resolver.openapi_resolver_builder:
        class: Linkin\Bundle\SwaggerResolverBundle\Builder\OpenApiResolverBuilder
        arguments:
            - !tagged { tag: linkin_swagger_resolver.normalizer }
            - !tagged { tag: linkin_swagger_resolver.validator }
            - '%linkin_swagger_resolver.enable_normalization%'
            - '@linkin_swagger_resolver.openapi_configuration'
            - '@linkin_swagger_resolver.parameter_type_matcher'
            - '@linkin_swagger_resolver.serializer'
            - '@?validator'

    linkin_swagger_resolver.openapi_configuration:
        class: Linkin\Bundle\SwaggerResolverBundle\Configuration\OpenApiConfiguration
        factory: '@linkin_swagger_resolver.openapi_configuration_factory'
        tags:
            - { name: kernel.cache_warmer }

    linkin_swagger_resolver.openapi_configuration_factory:
        class: Linkin\Bundle\SwaggerResolverBundle\Factory\OpenApiConfigurationFactory
        arguments:
            - '@router'
            - '@linkin_swagger_resolver.operation_parameter_merger'
            - '%linkin_swagger_resolver.oa_annotation_config%'
            - '%linkin_swagger_resolver.oa_file_config%'
            - '@linkin_swagger_resolver.serializer'
            - '@?linkin_swagger_resolver.cache'
            - '@?nelmio_api_doc.generator_locator'

    linkin_swagger_resolver.serializer:
        class: OpenApi\Serializer

    linkin_swagger_resolver.parameter_type_matcher:
        class: Linkin\Bundle\SwaggerResolverBundle\Matcher\ParameterTypeMatcher

    linkin_swagger_resolver.operation_parameter_merger:
        class: Linkin\Bundle\SwaggerResolverBundle\Merger\OperationParameterMerger
        arguments:
            - '@linkin_swagger_resolver.merge_strategy'
            - '@linkin_swagger_resolver.serializer'

    linkin_swagger_resolver.model_describers.object:
        class: Linkin\Bundle\SwaggerResolverBundle\Describer\ObjectModelDescriber
        arguments:
            - '@property_info'
            - '@annotation_reader'
            - !tagged { tag: nelmio_api_doc.object_model.property_describer }
            - '@linkin_swagger_resolver.doc_block'
            - ~
            - '@?serializer.name_converter.metadata_aware'
            - '@?marfa_tech_enumer.enum_registry'
        tags:
            - { name: nelmio_api_doc.model_describer, priority: 250 }

    linkin_swagger_resolver.doc_block:
        class: phpDocumentor\Reflection\DocBlockFactory
        factory: [ 'phpDocumentor\Reflection\DocBlockFactory', createInstance ]
